package com.ericho.compose.demo

object Route {
    const val HOME = "/vh"
    const val CONSTRAINT_LAYOUT = "/CONSTRAINT_LAYOUT"
    const val ANIMATION_COLOR = "/ANIMATION_COLOR"
    const val BASIC_ANIMATION_VISIBILITY = "/BASIC_ANIMATION_VISIBILITY"
    const val BASIC_ANIMATION_CONTENT = "/BASIC_ANIMATION_CONTENT"
    const val BASIC_ANIMATION_CONTENT2 = "/BASIC_ANIMATION_CONTENT2"
    const val BASIC_ANIMATION_CONTENT3 = "/BASIC_ANIMATION_CONTENT3"
    const val BASIC_ANIMATION_CONTENT4 = "/BASIC_ANIMATION_CONTENT4"

}